### ISSUE TITLE
Failure to parse scan ID from report breaks step entirely

### ISSUE THREAD

**Issue by usrme** [freckle/wiz-action#104]
On May 28th a successful scan yielded in a successful step execution, but the same scan performed today resulted in an error message (scan itself succeeded):

> Unable to parse Scan Id from report

At first I thought this was related to how Wiz has changed their encoding within the URLs:

* May 28th: `https://app.wiz.io/findings/cicd-scans#~(cicd_scan~'<ID>)`
* Today: `https://app.wiz.io/findings/cicd-scans#%7E%28cicd_scan%7E%27<ID>%29`

And that I could forego the job summary generation by removing `wiz-api-endpoint-url`, which would restore the step's functionality, but after removing the property the step still fails.

**Comment by pbrisbin** [comment]
Hi there- Would it be possible to share a screenshot of a failing build?

> how Wiz has changed their encoding within the URLs

For context, we recently _added_ logging of a URI-encoded results URL, but that's our own logging and not part of the CLI output that is being parsed here. A new version of the CLI changing its output in some other way could certainly explain the issue though.

> after removing the property the step still fails.

Unfortunately we parse the scan-id regardless of if we plan reach out to the API or not, since we also set it as an output. We could make this a bit more graceful and just warn on failure to parse while skipping anything that was dependent on it.

**Comment by usrme** [comment]
Thank you so much for the quick turnaround, really appreciate it!
